const i18Obj = {
  'en': {
    'home': 'Home',
    'about': 'About us',
    'practices': 'Practices',
    'contacts': 'Contact us',
    'hero-title': 'CAT & CAT Law Firm',
    'hero-text': 'We stayed to help you stay',
    'contact-us': 'Contact us',
    'our-team': 'Our team',
    'c-c-law-firm': 'CAT & CAT Law Firm',
    'our-team-description': 'includes three partners and the top-class team out of leading global law firms "Kitty & Roxy" and "Demourquis & Blackie".',
    'cat1-name': 'Cat Naughty',
    'cat1-description': 'Previously worked as a partner at Kitty & Roxy. Naughty has a vast experience of advising companies operating in the fishery and fish canning sector, as well as dry cat foods. Naughty has participated in the largest M&A transactions and is recognised as a leading corporate lawyer according to Legal 500, Chambers Global, Chambers Europe and Best Lawyers.',
    'cat2-name': 'Pride Debois',
    'cat2-description': "Headed the dispute resolution practice of the Moscow office of Demurquis. Pride specialises in international arbitration, as well as litigation in Russian and foreign courts. Pride holds a PhD degree in law and, for over 5 years, has lectured at the chair of criminal law at the Cat State University. He is recommended as a leading lawyer in arbitration, litigation and mediation by Who's Who.",
    'cat3-name': 'Ryka Blavatsky',
    'cat3-description': 'Worked as a senior lawyer of the corporate practice in the Moscow office of Demourquis & Blackie. She advises clients on soft cat foods and ambiguity. Ryka is recognised as "rising star" in corporate law by Legal 500 and Chambers 2021.',
    'our-practices': 'Our practices',
    'm-a-practice': 'Mergers & Acquisitions',
    'm-a-description1': 'Our corporate lawyers advise clients on various M&A matters, including:',
    'm-a-1': 'establishing joint ventures',
    'm-a-2': 'private equity transactions',
    'm-a-3': 'real estate and construction',
    'm-a-4': 'transactions in the energy and natural resources sectors',
    'm-a-5': 'compliance with the law',
    'm-a-description2': 'We acompany all stages of M&A transactions, including complex structuring, due diligence of assets, negotiating contractual documentation and obtaining regulatory approvals.',
    'l-a-practice': 'Litigation and Arbitration',
    'l-a-description1': 'Our dispute resolution lawyers advise and represent clients in resolving challenging major disputes through an out-of-court procedure or by recoursing to court or arbitration.',
    'l-a-description2': 'We have successfully resolved commercial, corporate, construction, infrastructure and real estate disputes, as well as disputes pertaining to financing and security instruments. In particular, we defend our clients in:',
    'l-a-1': 'international commercial arbitration',
    'l-a-2': 'litigations at Russian courts',
    'l-a-3': 'litigations at foreign courts',
    'l-a-description3': 'We maintain partner relationships with law firms outside Russia, which enables us to advise clients on matters involving foreign jurisdictions, including those of dogs.',
    'developed-by': 'Developed by:&nbsp;&nbsp;',
  },
  'ru': {    
    'home': 'Главная',
    'about': 'О нас',
    'practices': 'Практики',
    'contacts': 'Контакты',
    'hero-title': 'Юридическая фирма "КОТ & КОТ"',
    'hero-text': 'Мы остались, чтобы помочь остаться и вам',
    'contact-us': 'Напишите нам',
    'our-team': 'Наша команда',
    'c-c-law-firm': 'Юридическая фирма "КОТ & КОТ"',
    'our-team-description': 'включает трех партнеров, а также объединенную ими первоклассную команду юристов из ведущих глобальных юридических фирм "Китти энд Рокси" и "Демуркиз энд Блэки".',
    'cat1-name': 'Щен Борзый',
    'cat1-description': 'Ранее работал партнером корпоративной практики Китти энд Рокси. Щен имеет большой опыт консультирования компаний в секторе рыбы и рыбных ресурсов, а также твердых кормов. На счету Щена крупнейшие на российском рынке сделки по слияниям и поглощениям. Щен признан одним из ведущих корпоративных юристов по версии Legal 500, Chambers Global, Chambers Europe и Best Lawyers.',
    'cat2-name': 'Прайд Дебуа',
    'cat2-description': "Возглавлял практику разрешения споров московского офиса Демуркиз энд Блэки. Прайд специализируется на международных арбитражных разбирательствах, а также судебных разбирательствах в российских и иностранных судах. Прайд имеет степень кандидата юридических наук, более 5 лет преподавал на кафедре уголовного права юридического факультета КГУ им. Мурки. Он рекомендован в качестве ведущего юриста в области арбитража и медиации, международного арбитража и судебных разбирательств в России по версии Who's Who.",
    'cat3-name': 'Рыка Блаватски',
    'cat3-description': 'Работала старшим юристом корпоративной практики московского офиса Демуркиз энд Блэки. Консультирует клиентов по вопросам мягких кормов и однозначности. Рыка является признанным корпоративным юристом по версии Legal 500 и Chambers 2021 (в категории «rising star»).',
    'our-practices': 'Наши практики',
    'm-a-practice': 'Слияния и поглощения',
    'm-a-description1': 'Юристы нашей корпоративной практики консультируют клиентов по комплексным сделкам слияний и поглощений (M&A) и прочим корпоративным вопросам, включая:',
    'm-a-1': 'создание совместных предприятий (JV);',
    'm-a-2': 'инвестиции частного капитала;',
    'm-a-3': 'сделки в области недвижимости и строительства;',
    'm-a-4': 'сделки в области энергетики и природных ресурсов;',
    'm-a-5': 'нормативно-правовое соответствие.',
    'm-a-description2': 'Мы сопровождаем все этапы сделок M&A, включая комплексное структурирование, юридическую проверку активов, согласование сделочной документации и сопровождение получения регуляторных согласий.',
    'l-a-practice': 'Разрешение споров',
    'l-a-description1': 'Юристы нашей практики разрешения споров консультируют и представляют интересы клиентов при разрешении комплексных и крупнейших споров как на досудебной (претензионной), так и на юрисдикционной (судебной или арбитражной) стадиях.',
    'l-a-description2': 'Мы обладаем опытом успешного разрешения коммерческих, корпоративных, строительных, инфраструктурных споров, а также споров, связанных с недвижимостью, финансированием и предоставлением обеспечительных инструментов. В частности, мы защищаем наших клиентов:',
    'l-a-1': 'в международном коммерческом арбитраже (третейских судах);',
    'l-a-2': 'в судебных разбирательствах в российских судах;',
    'l-a-3': 'в судебных разбирательствах в иностранных государственных судах.',
    'l-a-description3': 'Мы сопровождаем все этапы сделок M&A, включая комплексное структурирование, юридическую проверку активов, согласование сделочной документации и сопровождение получения регуляторных согласий.',
    'developed-by': 'Разработано:&nbsp;&nbsp;',
  }
}
export default i18Obj;